### ISSUE TITLE
How to capture the Live feed from mars2000 150u area scan cams in WINDOWS.

### ISSUE THREAD

**Issue by s91-maker** [IamSierraCharlie/Contrastech_Python_SDK_for_Linux#4]
Hi,
   I have a very similar scenario like you had explained. And as you mentioned that, you had already got success with Windows machine by help of some 3rd party tools.
I am curious to know which 3rd party tool you have used and how you connected to it  and were you able to get the LIVE video stream captured at the programming end(python script). 
Do you have any suggestion where to look for the resource (python related solution or example). Thanks.

**Comment by IamSierraCharlie** [comment]
Hi,
I used activeusb.  It was software from A&Bsoft. 
http://www.ab-soft.com/

It's not free to use activeusb, but you can use a demo for 30 days

It may be possible to use this API in windows but I can't look at it until next week as I'm on the road for work.  I've not done any testing in it because I've worked mostly in Linux.

**Comment by IamSierraCharlie** [comment]
I spent some time looking at this today. Take a look at http://www.ab-soft.com/
If you install their software, it comes with documentation that shows you how to grab an image using their software in Python, C++. C# and other program languages.
As mentioned, in time, I'll look at seeing if my own API will work in Windows.  I'm only home for a day before being back on the road so I'm quite short of time at the moment sorry.

**Comment by IamSierraCharlie** [comment]
As of todays code pushes, you should probably be able to use the code in this repo to accomplish this.  If you run into issues, please file a bug report.
