### ISSUE TITLE
Windows_error

### ISSUE THREAD

**Issue by Fabian-Lieb** [IamSierraCharlie/Contrastech_Python_SDK_for_Linux#6]
Hey IamSierraCharlie,
Thanks for your great work!!! 
I also own a contrastech mars800-545um and want to make it work on windows. 
I tried your code but I have no experience with ctypes. 
As you mentioned i run in the same error to get the software trigger to go.
'''SoftTrigger getFrame fail! timeOut [1000]ms -> -1
  Not catastrophic so continuing
  You should only see this at the start of image grabbing
  OSError: exception: access violation reading 0x0000023D01959FF0'''
I am trying to get familiar with cytpes and will also continue with youre work....

**Comment by IamSierraCharlie** [comment]
Hi
Given your camera has a different resolution to mine, try changing the variables
Offset_x and offset_y to 0 and also set the image width and height as well.  I think your camera res should be 800 X 600? So try that res to begin with.  These settings are in the imagegrabdemo.py file
Lines 11 thru 14.
Start with those changes and let me know the outcome.

I'm on the road for work. No access to my PC.  If it's still not working,. I'll take a better look when I'm home in a few days.

**Comment by Fabian-Lieb** [comment]
Wow Thank you very much!!! Its working now....
I will be working on a project with the camera from now on.
Maybe i can also share some information in the future....
So thanks for you're great work and support you helped me verry much.
